menu:
    Blog: /
    Archive: /archives/
    Twitter: https://twitter.com/moo_less
    GitHub: https://github.com/zhangzhanqicixi
    About: /about
    Rss: /atom.xml
    # donation: /atom.xml


favicon: /st.png
logo: /st.png

# Comment
# e.g disqus: seansun
disqus: timeline229

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2018
